# -*- coding: utf-8 -*-
"""Yash Sinha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1efs1NbSnpWRUFLz8fUdqvOkLSBnZCQkE
"""

a=[18, 20, 8, 16, 4, 10, 12, 3]
a.sort()
print("Second largest number = ",a[6])
num=a[6]
count=0
while(num>0):
  if num%2==0:
    num=num/2
  else: 
    num=num-1
  count+=1
print("Number of count to reduce the number to zero is : ",count)